" list of online vimrc used :
" * github.com/victormours/dotfiles
" * github.com/alepez/dotfiles/tree/master/vim 

" automatic reloading of .vimrc 
autocmd! bufwritepost .vimrc source %

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
filetype off        " required

" The mapleader has to be set before vundle starts loading plugins.
let mapleader = "\<Space>"

" escape insert mode easily
" http://vim.wikia.com/wiki/Avoid_the_escape_key
imap <leader><tab> <Esc>

""""""""""
""" VUNDLE
""""""""""
"
" see Vundle documentation here: https://github.com/VundleVim/Vundle.vim
"
" set runtime path to include Vundle and initialise
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')

" let Vundle manage itself (required)
Plugin 'gmarik/Vundle.vim'

" Plugins here ... 
Plugin 'tomasr/molokai'                   " color scheme
Plugin 'Valloric/YouCompleteMe'           " code completion
Plugin 'scrooloose/nerdtree'              " tree explorer
Plugin 'Xuyuanp/nerdtree-git-plugin'      " git status in nerdtree
Plugin 'octol/vim-cpp-enhanced-highlight' " advanced C++ syntax highlighting
Plugin 'ctrlpvim/ctrlp.vim'               " fuzzy finder
Plugin 'airblade/vim-gitgutter'           " git diff open files
Plugin 'godlygeek/tabular'                " most come before vim-markdown
Plugin 'plasticboy/vim-markdown'          " .md syntax highlighting, matching and mappings
Plugin 'JamshedVesuna/vim-markdown-preview' " preview markdown in the browser
Plugin 'rdnetto/YCM-Generator'            " generate conf.py files for YCM 
Plugin 'scrooloose/nerdcommenter'         " allows for easy commenting
Plugin 'tpope/vim-fugitive'               " vim-fugitive for git

" All of your Plugins must be added before this line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
" filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line ... 

" ================ General Config ===================
"
" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

syntax enable
syntax on

set relativenumber  " show relative line numbers
set number			    " show absolute line number of current line
set showmatch		    " show matching brackets [] {} ()
set history=1000    " store lots of :cmdline history
set showmode        " show current mode down the bottom
set autoread		    " reload files changed outside of vim
set scrolloff=3     " Keep 3 lines below and above the cursor
set mouse=a         " enable use of mouse

set clipboard=unnamed	  " allow paste from mac clipboard

" switch panes 
nnoremap <leader>w <C-w>w

" list buffers
nnoremap <leader>ls :ls<CR>
" close the current buffer
nnoremap <leader>bd :bn\|bd #<CR>
" close all buffers except current
nnoremap <leader>bdd :%bd|e#<CR>
" scrol next/previous buffers
nnoremap <leader>bn :bn<CR>
nnoremap <leader>bp :bp<CR>

" jump to end of line with ctrl-e in insert mode
inoremap <C-e> <C-o>$
" jump to start of line with ctrl-a in insert mode
inoremap <C-a> <C-o>0

" =================================
" copy file path to clipboard
" https://vi.stackexchange.com/a/3687
nnoremap <leader>c :let @+=expand('%:p')<CR>

" Copy filepaths to system clipboard. Commands from this post on StackOverflow : 
" https://stackoverflow.com/questions/916875/yank-file-name-path-of-current-buffer-in-vim
" copy current file name (relative/absolute) to system clipboard
" MacOSX version
if has("mac") || has("gui_macvim") || has("gui_mac")
  " relative path  (src/foo.txt)
  "nnoremap <leader>cf :let @*=expand("%")<CR>
  " absolute path  (/something/src/foo.txt)
  "nnoremap <leader>cF :let @*=expand("%:p")<CR>
  " filename       (foo.txt)
  "nnoremap <leader>ct :let @*=expand("%:t")<CR>
  " directory name (/something/src)
  "nnoremap <leader>ch :let @*=expand("%:p:h")<CR>
endif
" Unix/Linux version
if has("gui_gtk") || has("gui_gtk2") || has("gui_gnome") || has("unix")
  " relative path (src/foo.txt)
  "nnoremap <leader>cf :let @+=expand("%")<CR>
  " absolute path (/something/src/foo.txt)
  "nnoremap <leader>cF :let @+=expand("%:p")<CR>
  " filename (foo.txt)
  "nnoremap <leader>ct :let @+=expand("%:t")<CR>
  " directory name (/something/src)
  "nnoremap <leader>ch :let @+=expand("%:p:h")<CR>
endif
" =================================

" Ensure Quickfix window always on the bottom and
" taking the whole horizontal space.
autocmd FileType qf wincmd J

" ================ Turn Off Swap Files ==============
"
set noswapfile
set nobackup
set nowb

" OR store temporary files in a central location
" as suggested here : 
"set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
"set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" ================ Search ===========================
"
set incsearch		  " incremental search mode
set hlsearch		  " highlight search things
set ignorecase		" ignorecase when searching
set smartcase		  " only works when ignorecase on

" quickly clear search highlights 
nnoremap <silent> <leader>nh :nohlsearch<CR>

" ================ Replace ==========================
"
" replace all occurances of word under the cursor
" http://vim.wikia.com/wiki/Search_and_replace_the_word_under_the_cursor
nnoremap <leader>sr :%s/\<<C-r><C-w>\>//g<Left><Left>

" ================ Indentation ======================
set autoindent		  " align new line indent with previous line
set expandtab       " tab is replaced with spaces
set tabstop=2		    " number of spaces <TAB> counts for
set shiftwidth=2    " operation >> indents 2 spaces; << unindents 2 spaces

" ================ Python Format ====================
"
" Automatically format the current python file using autopep8. 
" autopep8 must be installed. See  https://pypi.python.org/pypi/autopep8
nnoremap <leader>pf :! autopep8 --in-place --aggressive % <CR>

" ======= Display output of Shell Command  ==========
"
" Copy the output of any Shell command into a Scratch buffer.
" Usage :Shell ls-al
" http://vim.wikia.com/wiki/Display_output_of_shell_commands_in_new_window
command! -complete=shellcmd -nargs=+ Shell call s:RunShellCommand(<q-args>)

function! s:RunShellCommand(cmdline)
  echo a:cmdline
  let expanded_cmdline = a:cmdline
  for part in split(a:cmdline, ' ')
     if part[0] =~ '\v[%#<]'
        let expanded_part = fnameescape(expand(part))
        let expanded_cmdline = substitute(expanded_cmdline, part, expanded_part, '')
     endif
  endfor
  botright new
  setlocal buftype=nofile bufhidden=wipe nobuflisted noswapfile nowrap
  call setline(1, 'You entered:    ' . a:cmdline)
  call setline(2, 'Expanded Form:  ' .expanded_cmdline)
  call setline(3,substitute(getline(2),'.','=','g'))
  execute '$read !'. expanded_cmdline
  setlocal nomodifiable
  1
endfunction

""""""""""""""""""""""""""""""""""""
" ====== VIM PLUGIN CONFIG =========
""""""""""""""""""""""""""""""""""""
"
"" ========== UI colourscheme ======
set background=dark
colorscheme molokai

" =========== NERDTree =============
" https://medium.com/@victormours/a-better-nerdtree-setup-3d3921abc0b9#.hulkzoakb
"
" Open NERDTree by deafult when we open vim
"autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 | NERDTree | endif

" Easily toggle NERDTree
nnoremap <leader>nt :NERDTreeToggle<CR>

" Easily open NerdTree on the file you’re editing
nnoremap <silent> <leader>nf :NERDTreeFind<CR>

" =========== GitGutter ============
" Activate by defualt 
let g:gitgutter_enabled=1

" =========== VimFugitive ==========
" fugitive git bindings
" https://www.reddit.com/r/vim/comments/21f4gm/best_workflow_when_using_fugitive/cgciltz
nnoremap <leader>ga :Git add %:p<CR><CR>
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gc :Gcommit -v -q<CR>
nnoremap <leader>gt :Gcommit -v -q %:p<CR>
nnoremap <leader>gd :Gvdiff<CR>
nnoremap <leader>ge :Gedit<CR>
nnoremap <leader>gr :Gread<CR>
nnoremap <leader>gw :Gwrite<CR><CR>
nnoremap <leader>gl :silent! Glog<CR>:bot copen<CR>
nnoremap <leader>gp :Ggrep<Space>
nnoremap <leader>gm :Gmove<Space>
nnoremap <leader>gbr :Git branch<Space>
nnoremap <leader>gco :Git checkout<Space>
nnoremap :gpush :Dispatch! git push<CR>
nnoremap :gpull :Dispatch! git pull<CR>

" =========== CtrlP ================
" order matching files top to bottom
let g:ctrlp_match_window = 'bottom,order:ttb'

" always open files in new buffers.
let g:ctrlp_switch_buffer = 1
" if we change the working directory CtrlP should respect that change.
let g:ctrlp_working_path_mode = 1

" tell CtrlP to run an external command to find matching files
" and use ag (must have this installed) to make things wicked fast !
" see here: https://dougblack.io/words/a-good-vimrc.html#ctrlp-section
let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'

" =========== Markdown =============
" disable the folding configuration
let g:vim_markdown_folding_disabled = 1
" prevent foldtext from being set
let g:vim_markdown_override_foldtext = 0

" use grip (https://github.com/joeyespo/grip) for GitHub flavoured Markdown
" (https://help.github.com/categories/writing-on-github/) 
" Note. grip must be installed (eg. on Mac use 'brew install grip')
let vim_markdown_preview_github=1
" remap vim-markdown-preview key bindins
let vim_markdown_preview_hotkey='<leader>md'
" use Google Chrome to preview markdown
let vim_markdown_preview_browser='Google Chrome'
" show images in preview
let vim_markdown_preview_toggle=1
" delete the generated html file once in the browser
let vim_markdown_preview_temp_file=1


" =========== python ===============

let g:pymode_python = 'python3'

" =========== clang-format =========
" If 'clang-format' is not in PATH, specify its path
"let g:clang_format_binary = '<absolute-path-to-clang-format>'

" Use google c++ style: https://google.github.io/styleguide/cppguide.html
" Default is to use the .clang-format file in the tree otherwise use fallback_style
" Use -style=file to load style configuration from .clang-format file located in one of the parent directories of the source file (or current directory for stdin).
let g:clang_format_style = 'file'
" let g:clang_format_style = '{ BasedOnStyle: llvm, IndentWidth: 4 }'
let g:clang_format_fallback_style = 'Google'

" map key-shortcut for easy use Note that we are using the python3 script. See
" https://gist.github.com/fasiha/8af2a4f719812319934947124bb63afd for details.
" support for NORMAL and VISUAL modes
map <leader>cf :py3f ~/.vim/clang_format.py<CR>
" support for INSERT mode 
imap <C-I> <c-o>:py3f ~/.vim/clang_format.py<CR>

:function  ClangFormatFile()
:  let l:lines="all"
:  py3f ~/.vim/clang_format.py
:endfunction

" NORMAL mode - clang-format all lines
nmap <leader>cff :call ClangFormatFile()<CR>

" =========== YouCompleteMe ========
" See GitHub for documentation: https://github.com/Valloric/YouCompleteMe 
" http://www.alexeyshmalko.com/2014/youcompleteme-ultimate-autocomplete-plugin-for-vim/
"
" For default options see here: https://github.com/Valloric/YouCompleteMe#options
"
" extras auto-completion file for C family - (we get these as minimum)
" taken from https://github.com/rasendubi/dotfiles/blob/master/.vim/.ycm_extra_conf.py
" more complete version: https://github.com/Valloric/ycmd/blob/master/cpp/ycm/.ycm_extra_conf.py
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"

" use first python executable found in PATH. Useful in a virtual environment - just
" start vim in that directory to provide completions for packages in the virtual env.
" https://github.com/Valloric/YouCompleteMe/blob/master/README.md#python-semantic-completion
let g:ycm_python_binary_path = 'python'

" automatically close the preview window.
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1

" add key mappings
" perform the 'most sensible' GoTo operation it can
nnoremap <leader>jd :YcmCompleter GoTo<CR>
" =================================
" /END
